FROM node:18.20.5-bullseye

WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force && \
    npm install --legacy-peer-deps

COPY . .

RUN npm install @next/swc-linux-x64-gnu --legacy-peer-deps

RUN npm run build

EXPOSE 3000

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
