FROM node:18.20.5-bullseye

WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force && \
    npm install --legacy-peer-deps

COPY . .

EXPOSE 3000

# Use development mode by default
ENV NODE_ENV=development

# Use npm run dev for development
CMD ["npm", "run", "dev"]
