// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetArticlesData, GetArticlesResponse, PostArticlesData, PostArticlesResponse, GetArticlesByIdData, GetArticlesByIdResponse, PatchArticlesByIdData, PatchArticlesByIdResponse, DeleteArticlesByIdData, DeleteArticlesByIdResponse, PostArticlesGenerateData, PostArticlesGenerateResponse, PostArticlesByIdTranslateData, PostArticlesByIdTranslateResponse, PostArticlesByIdSummarizeData, PostArticlesByIdSummarizeResponse, PostArticlesByIdTagData, PostArticlesByIdTagResponse } from './types.gen';

export class ArticlesService {
    /**
     * Get all articles
     * @param data The data for the request.
     * @param data.title Filter by title
     * @param data.author Filter by author
     * @param data.limit Number of results per page
     * @param data.page Page number
     * @returns Article List of articles
     * @throws ApiError
     */
    public static getArticles(data: GetArticlesData = {}): CancelablePromise<GetArticlesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/articles',
            query: {
                title: data.title,
                author: data.author,
                limit: data.limit,
                page: data.page
            }
        });
    }
    
    /**
     * Create an article
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Article Article created
     * @throws ApiError
     */
    public static postArticles(data: PostArticlesData): CancelablePromise<PostArticlesResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/articles',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Get article by ID
     * @param data The data for the request.
     * @param data.id Article ID
     * @returns Article Article details
     * @throws ApiError
     */
    public static getArticlesById(data: GetArticlesByIdData): CancelablePromise<GetArticlesByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/articles/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * Update an article
     * @param data The data for the request.
     * @param data.id Article ID
     * @param data.requestBody
     * @returns Article Article updated
     * @throws ApiError
     */
    public static patchArticlesById(data: PatchArticlesByIdData): CancelablePromise<PatchArticlesByIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/articles/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Delete an article
     * @param data The data for the request.
     * @param data.id Article ID
     * @returns void Article deleted
     * @throws ApiError
     */
    public static deleteArticlesById(data: DeleteArticlesByIdData): CancelablePromise<DeleteArticlesByIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/articles/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * Generate an article using AI
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Article Generated article
     * @throws ApiError
     */
    public static postArticlesGenerate(data: PostArticlesGenerateData): CancelablePromise<PostArticlesGenerateResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/articles/generate',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Translate an article using AI
     * @param data The data for the request.
     * @param data.id Article ID
     * @param data.requestBody
     * @returns Article Translated article
     * @throws ApiError
     */
    public static postArticlesByIdTranslate(data: PostArticlesByIdTranslateData): CancelablePromise<PostArticlesByIdTranslateResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/articles/{id}/translate',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Summarize an article using AI
     * @param data The data for the request.
     * @param data.id Article ID
     * @param data.requestBody
     * @returns Article Summarized article
     * @throws ApiError
     */
    public static postArticlesByIdSummarize(data: PostArticlesByIdSummarizeData): CancelablePromise<PostArticlesByIdSummarizeResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/articles/{id}/summarize',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Generate tags for an article using AI
     * @param data The data for the request.
     * @param data.id Article ID
     * @param data.requestBody
     * @returns Article Tagged article
     * @throws ApiError
     */
    public static postArticlesByIdTag(data: PostArticlesByIdTagData): CancelablePromise<PostArticlesByIdTagResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/articles/{id}/tag',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}