// This file is auto-generated by @hey-api/openapi-ts

export type Article = {
    id?: string;
    title: string;
    titleFr?: string;
    content: string;
    contentEn?: string;
    contentFr?: string;
    author: string;
    publishedDate?: string;
    tags?: Array<(string)>;
    category?: string;
    status?: 'draft' | 'published' | 'archived';
    relatedCompanies?: Array<(string)>;
    marketData?: string;
    summary?: string;
};

export type status = 'draft' | 'published' | 'archived';

export type ArticleAiRequest = {
    id?: string;
    pressRelease?: string;
    language?: string;
};

export type GetArticlesData = {
    /**
     * Filter by author
     */
    author?: string;
    /**
     * Number of results per page
     */
    limit?: number;
    /**
     * Page number
     */
    page?: number;
    /**
     * Filter by title
     */
    title?: string;
};

export type GetArticlesResponse = (Array<Article>);

export type PostArticlesData = {
    requestBody: Article;
};

export type PostArticlesResponse = (Article);

export type GetArticlesByIdData = {
    /**
     * Article ID
     */
    id: string;
};

export type GetArticlesByIdResponse = (Article);

export type PatchArticlesByIdData = {
    /**
     * Article ID
     */
    id: string;
    requestBody: Article;
};

export type PatchArticlesByIdResponse = (Article);

export type DeleteArticlesByIdData = {
    /**
     * Article ID
     */
    id: string;
};

export type DeleteArticlesByIdResponse = (void);

export type PostArticlesGenerateData = {
    requestBody: ArticleAiRequest;
};

export type PostArticlesGenerateResponse = (Article);

export type PostArticlesByIdTranslateData = {
    /**
     * Article ID
     */
    id: string;
    requestBody: ArticleAiRequest;
};

export type PostArticlesByIdTranslateResponse = (Article);

export type PostArticlesByIdSummarizeData = {
    /**
     * Article ID
     */
    id: string;
    requestBody: ArticleAiRequest;
};

export type PostArticlesByIdSummarizeResponse = (Article);

export type PostArticlesByIdTagData = {
    /**
     * Article ID
     */
    id: string;
    requestBody: ArticleAiRequest;
};

export type PostArticlesByIdTagResponse = (Article);